### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by stsci-sienkiew** [brandon-rhodes/pyzmq-static#5]
This is Python 2.7.3 compiled from source on Red Hat Enterprise 5 Linux.  I downloaded pyzmq-static-2.1.11.2.tar.gz and used "python setup.py install" to install it.  There are no apparent errors in the output from setup.py, but 

```
$ python
Python 2.7.3 (default, Jul 17 2012, 13:51:57) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-50)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq.eventloop
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/eventloop/__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 56, in <module>
    from zmq.eventloop.platform.auto import set_close_exec, Waker
ImportError: No module named platform.auto
>>> 
```

Running the tests shows:

```
$ nosetests zmq.tests
..............S.......E...E...E................................................E
======================================================================
ERROR: test eventloop imports
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/tests/test_imports.py", line 65, in test_eventloop
    import zmq.eventloop
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/eventloop/__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 48, in <module>
    from zmq.eventloop import stack_context
ImportError: cannot import name stack_context

======================================================================
ERROR: Failure: ImportError (No module named platform.auto)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/tests/test_ioloop.py", line 30, in <module>
    from zmq.eventloop import ioloop
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/eventloop/__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 56, in <module>
    from zmq.eventloop.platform.auto import set_close_exec, Waker
ImportError: No module named platform.auto

======================================================================
ERROR: Failure: ImportError (No module named rebuffer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/tests/test_message.py", line 36, in <module>
    from zmq.utils.rebuffer import array_from_buffer
ImportError: No module named rebuffer

======================================================================
ERROR: Failure: ImportError (cannot import name stack_context)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/tests/test_zmqstream.py", line 32, in <module>
    from zmq.eventloop import ioloop, zmqstream
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/eventloop/__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 48, in <module>
    from zmq.eventloop import stack_context
ImportError: cannot import name stack_context

----------------------------------------------------------------------
Ran 80 tests in 9.159s

FAILED (SKIP=1, errors=4)
```

I'm not really sure what to make of this.  There isn't anything obviously wrong, except that some of the things that the tests import just aren't there.  I suppose this could be missing files, or it could be bugs in the original pyzmq.

**Comment by jasonfield** [comment]
I think there is a missing platform folder in https://github.com/brandon-rhodes/pyzmq-static/tree/master/zmq/eventloop - it is there in 2.1.11 for pyzmq - https://github.com/zeromq/pyzmq/tree/v2.1.11/zmq/eventloop. If you copy the platform folder into your local pyzmq-static install it should all work fine.

**Comment by jasonfield** [comment]
I have added the missing files in a fork (https://github.com/jasonfield/pyzmq-static) and submitted a pull request.

**Comment by stsci-sienkiew** [comment]
I also needed to add the package zmq.eventloop.platform to the list of packages:

--- a/setup.py
+++ b/setup.py
@@ -194,7 +194,7 @@ setup(name='pyzmq-static',
       url='https://github.com/brandon-rhodes/pyzmq-static',
       cmdclass = cmdclass,
       packages = ['zmq', 'zmq.tests', 'zmq.eventloop', 'zmq.log', 'zmq.core',
-                  'zmq.devices', 'zmq.utils'],
-                  'zmq.devices', 'zmq.utils', 'zmq.eventloop.platform' ],
     package_data = package_data,
     ext_modules= extensions,
     classifiers = [

**Comment by stsci-sienkiew** [comment]
Let's see if I can make that come out legible.  Guess not - "preview" doesn't do anything.  Anyway, I added 'zmq.eventloop.platform' to the list where it says packages = [ ...

**Comment by brandon-rhodes** [comment]
Beyond our wildest dreams, our work has been accepted into the main "pyzmq" project — so its maintainer is now the one in charge of which files do and don't get included in the distribution. And, from what I've seen, he is way better at it than I was!  But please do try installing the new 2.2.0.1 version of "pyzmq" and see whether the files I left our are correctly present in the official distribution. And thanks for using pyzmq-static, and please add bugs against the main pyzmq project if its new installation logic for some reason does not work for you, and feel free to point me at your issue so that I can jump in and help.
