### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?

### ISSUE THREAD

**Issue by daryltucker** [brandon-rhodes/pyzmq-static#7]
```bash
pip install pyzmq-static==2.1.11.2
Collecting pyzmq-static==2.1.11.2
  Downloading pyzmq-static-2.1.11.2.tar.gz (426 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 426.0/426.0 kB 8.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Daryl Tucker\AppData\Local\Temp\pip-install-yl113aq6\pyzmq-static_06325e0a0ee940e3bd1527af1a4bb409\setup.py", line 179, in <module>
          long_description = open('README.rst').read().decode('utf-8')
      AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

This happens when running `pip install pyzmq-static` or `pip install pyzmq-static==2.1.11.2`, the later being the example on the README.

**Comment by daryltucker** [comment]
Oh, I see.  This was merged upstream many years ago.  My apologies for the noise.

**Comment by brandon-rhodes** [comment]
Thanks for coming back to the issue to close it once you realized the project status!
